apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-secret-{{ .Values.env }}
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
type: Opaque
data:
  NV_VAULT_ROLEID: {{ .Values.NV_VAULT_ROLEID | b64enc }}
  NV_VAULT_SECRETID: {{ .Values.NV_VAULT_SECRETID | b64enc }}
  NVSF_CLIENT_ID: {{ .Values.NVSF_CLIENT_ID | b64enc }}
  NVSF_CLIENT_ID_NONPRD: {{ .Values.NVSF_CLIENT_ID_NONPRD | b64enc }}
#  DD_LOGS_INJECTION: {{ .Values.NV_VAULT_SECRETID | b64enc }}
#  DD_PROFILING_ENABLED: {{ .Values.NV_VAULT_SECRETID | b64enc }}
  LLM_GATEWAY_CLIENT_ID: {{ .Values.LLM_GATEWAY_CLIENT_ID | b64enc }}
  LLM_GATEWAY_CLIENT_SECRET: {{ .Values.LLM_GATEWAY_CLIENT_SECRET | b64enc }}
  IT_SUPPORT_NVAUTH_ACCOUNT_TOKEN: {{ .Values.IT_SUPPORT_NVAUTH_ACCOUNT_TOKEN | b64enc }}
  IT_SUPPORT_BEARER_TOKEN: {{ .Values.IT_SUPPORT_BEARER_TOKEN | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-creds-{{ .Values.env }}
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}